[package]
name = "looking_glass"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.23.0"
egui-wgpu = { version = "0.23.0", features = ["winit"] }
egui-winit = "0.23.0"
gltf = "1.4.0"
pollster = "0.3.0"
raw-window-handle = "0.5.2"
rfd = "0.12.1"
wgpu = "0.17.1"
winit = "0.28.7"
