[workspace]
members = ["apps/editor"]
[package]
name = "serenity"
authors = ["Matthew Berger <matthewjordanberger@gmail.com>"]
edition = "2021"
homepage = "https://github.com/matthewjberger/serenity"
license = "MIT"
repository = "https://github.com/matthewjberger/serenity"
version = "0.1.0"

[dependencies]
bytemuck = "1.14.0"
egui = "0.23.0"
egui-wgpu = { version = "0.23.0", features = ["winit"] }
egui-winit = "0.23.0"
egui_extras = { version = "0.23.0", features = ["all_loaders"] }
env_logger = "0.10.1"
gltf = { version = "1.4.0", features = ["KHR_lights_punctual", "names"] }
image = "0.24.7"
log = "0.4.20"
nalgebra = "0.32.3"
nalgebra-glm = { version = "0.18.0", features = [
    "serde-serialize",
    "convert-bytemuck",
] }
petgraph = { version = "0.6.4", features = ["serde-1"] }
pollster = "0.3.0"
raw-window-handle = "0.5.2"
serde = { version = "1.0.193", features = ["derive"] }
thiserror = "1.0.53"
uuid = { version = "1.6.1", features = ["v4"] }
wgpu = "0.17.1"
winit = "0.28.7"
